import { Type } from "typebox"; import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin"; import { createHubSpotClient } from "./client.js"; import { resolveConfig, type HubSpotPluginConfig } from "./config.js"; import * as op from "./operations.js";
const configSchema = Type.Object({ accessToken: Type.Union([Type.String({ minLength: 1 }), Type.Object({ source: Type.Union([Type.Literal("env"), Type.Literal("file"), Type.Literal("exec")]), provider: Type.String(), id: Type.String() }, { additionalProperties: false })], { description: "HubSpot private app token. Use a host-managed SecretRef, never chat or source control." }), portalId: Type.Optional(Type.String({ pattern: "^[0-9]+$" })), timezone: Type.Optional(Type.String({ description: "Optional IANA timezone; no default." })) }, { additionalProperties: false });
const params = Type.Object({ action: Type.String(), id: Type.Optional(Type.String()), email: Type.Optional(Type.String()), idProperty: Type.Optional(Type.String()), objectType: Type.Optional(Type.String()), properties: Type.Optional(Type.Unknown()), filterGroups: Type.Optional(Type.Unknown()), query: Type.Optional(Type.String()), sorts: Type.Optional(Type.Unknown()), limit: Type.Optional(Type.Number()), after: Type.Optional(Type.Union([Type.String(), Type.Number()])), associations: Type.Optional(Type.Unknown()), body: Type.Optional(Type.String()), subject: Type.Optional(Type.String()), timestamp: Type.Optional(Type.String()), fromType: Type.Optional(Type.String()), fromId: Type.Optional(Type.String()), toType: Type.Optional(Type.String()), toId: Type.Optional(Type.String()), associationTypeId: Type.Optional(Type.Number()), associationCategory: Type.Optional(Type.String()), pipelineId: Type.Optional(Type.String()), pipeline: Type.Optional(Type.Unknown()), propertyName: Type.Optional(Type.String()), ownerId: Type.Optional(Type.String()), listId: Type.Optional(Type.String()), recordIds: Type.Optional(Type.Array(Type.String())), workflowId: Type.Optional(Type.String()), contactId: Type.Optional(Type.String()) }, { additionalProperties: false });
const actions = (values: string[]) => Type.Object({ ...params.properties, action: Type.Union(values.map((v) => Type.Literal(v))) }, { additionalProperties: false });
async function run(handler: any, p: unknown, cfg: HubSpotPluginConfig, signal?: AbortSignal) { signal?.throwIfAborted(); const resolved = resolveConfig(cfg); return { data: await handler(createHubSpotClient({ token: resolved.token, signal }), resolved, (p ?? {}) as Record<string, any>) }; }
const definitions: Array<[string, string, any, any]> = [
  ["hs_status", "HubSpot Status", Type.Object({}, { additionalProperties: false }), op.status], ["hs_contacts", "HubSpot Contacts", actions(["search","list","get","create","update","archive"]), op.contacts], ["hs_companies", "HubSpot Companies", actions(["search","list","get","create","update","archive"]), op.companies], ["hs_deals", "HubSpot Deals", actions(["search","list","get","create","update","archive"]), op.deals], ["hs_tickets", "HubSpot Tickets", actions(["search","list","get","create","update","archive"]), op.tickets], ["hs_notes", "HubSpot Notes", actions(["search","list","get","create","update","archive"]), op.notes], ["hs_tasks", "HubSpot Tasks", actions(["search","list","get","create","update","archive","complete"]), op.tasks], ["hs_emails", "HubSpot Logged Emails", actions(["search","list","get","create","update","archive"]), op.emails], ["hs_calls", "HubSpot Calls", actions(["search","list","get","create","update","archive"]), op.calls], ["hs_meetings", "HubSpot Meetings", actions(["search","list","get","create","update","archive"]), op.meetings], ["hs_associations", "HubSpot Associations", actions(["list","create","delete"]), op.associations], ["hs_pipelines", "HubSpot Pipelines", actions(["list","get","create"]), op.pipelines], ["hs_properties", "HubSpot Properties", actions(["list","get","create"]), op.properties], ["hs_owners", "HubSpot Owners", actions(["list","get"]), op.owners], ["hs_lists", "HubSpot Lists", actions(["list","get","add_memberships","remove_memberships"]), op.lists], ["hs_workflows", "HubSpot Workflows", actions(["list","enroll","unenroll"]), op.workflows], ["hs_objects", "HubSpot Custom Objects", actions(["search","list","get","create","update","archive"]), op.objects],
];
export default defineToolPlugin({ id: "arcforgelabs-hubspot", name: "HubSpot by Arc Forge", description: "Unofficial HubSpot CRM integration maintained by Arc Forge Labs; not affiliated with or endorsed by HubSpot, Inc.", configSchema, tools: (tool) => definitions.map(([name, label, parameters, handler]) => tool({ name, label, description: `Operate HubSpot ${label.replace("HubSpot ", "").toLowerCase()}.`, parameters, async execute(p, c, context) { return run(handler, p, c, context.signal); } })) });
